version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=msgym
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=posgres
    volumes:
      - ./uploads:/var/www/html/uploads
      - ./xls:/var/www/html/xls

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: msgym
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: posgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./msgym_script.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: